# Rules: https://eslint.org/docs/rules/
# Version: 7.32.0
# Last updated: 2021-09-05

rules:
  # Possible Errors
  for-direction:
    - error
  getter-return:
    - error
    - allowImplicit: false
  no-async-promise-executor:
    - error
  no-await-in-loop:
    - error
  no-compare-neg-zero:
    - error
  no-cond-assign:
    - error
    - except-parens
  no-console:
    - error
  no-constant-condition:
    - error
    - checkLoops: true
  no-control-regex:
    - error
  no-debugger:
    - error
  no-dupe-args:
    - error
  no-dupe-else-if:
    - error
  no-dupe-keys:
    - error
  no-duplicate-case:
    - error
  no-empty:
    - error
    - allowEmptyCatch: false
  no-empty-character-class:
    - error
  no-ex-assign:
    - error
  no-extra-boolean-cast:
    - error
    - enforceForLogicalOperands: true
  no-extra-parens:
    - error
    - all
  no-extra-semi:
    - error
  no-func-assign:
    - error
  no-import-assign:
    - error
  no-inner-declarations:
    - error
    - both
  no-invalid-regexp:
    - error
  no-irregular-whitespace:
    - error
    - skipStrings: false
      skipComments: false
      skipRegExps: false
      skipTemplates: false
  no-loss-of-precision:
    - error
  no-misleading-character-class:
    - error
  no-obj-calls:
    - error
  no-promise-executor-return:
    - error
  no-prototype-builtins:
    - error
  no-regex-spaces:
    - error
  no-setter-return:
    - error
  no-sparse-arrays:
    - error
  no-template-curly-in-string:
    - error
  no-unexpected-multiline:
    - error
  no-unreachable:
    - error
  no-unreachable-loop:
    - error
  no-unsafe-finally:
    - error
  no-unsafe-negation:
    - error
    - enforceForOrderingRelations: true
  no-unsafe-optional-chaining:
    - error
    - disallowArithmeticOperators: true
  no-useless-backreference:
    - error
  require-atomic-updates:
    - error
  use-isnan:
    - error
    - enforceForSwitchCase: true
      enforceForIndexOf: true
  valid-typeof:
    - error
    - requireStringLiterals: true

  # Best Practices
  accessor-pairs:
    - error
    - setWithoutGet: true
      getWithoutSet: false
      enforceForClassMembers: true
  array-callback-return:
    - error
    - allowImplicit: false
      checkForEach: true
  block-scoped-var:
    - error
  class-methods-use-this:
    - error
  complexity:
    - warn
    - max: 20
  consistent-return:
    - error
    - treatUndefinedAsUnspecified: false
  curly:
    - error
    - all
  default-case:
    - error
  default-case-last:
    - error
  default-param-last:
    - error
  dot-location:
    - error
    - property
  dot-notation:
    - error
    - allowKeywords: false
  eqeqeq:
    - error
    - always
  grouped-accessor-pairs:
    - warn
    - getBeforeSet
  guard-for-in:
    - error
  max-classes-per-file:
    - off
  no-alert:
    - error
  no-caller:
    - error
  no-case-declarations:
    - error
  no-constructor-return:
    - error
  no-div-regex:
    - error
  no-else-return:
    - error
    - allowElseIf: false
  no-empty-function:
    - error
  no-empty-pattern:
    - error
  no-eq-null:
    - error
  no-eval:
    - error
    - allowIndirect: false
  no-extend-native:
    - error
  no-extra-bind:
    - error
  no-extra-label:
    - error
  no-fallthrough:
    - error
  no-floating-decimal:
    - error
  no-global-assign:
    - error
  no-implicit-coercion:
    - error
    - boolean: true
      number: true
      string: true
      disallowTemplateShorthand: true
  no-implicit-globals:
    - error
  no-implied-eval:
    - error
  no-invalid-this:
    - error
    - capIsConstructor: false
  no-iterator:
    - error
  no-labels:
    - error
    - allowLoop: false
      allowSwitch: false
  no-lone-blocks:
    - error
  no-loop-func:
    - error
  no-magic-numbers:
    - off
  no-multi-spaces:
    - error
    - ignoreEOLComments: false
  no-multi-str:
    - error
  no-new:
    - error
  no-new-func:
    - error
  no-new-wrappers:
    - error
  no-nonoctal-decimal-escape:
    - error
  no-octal:
    - error
  no-octal-escape:
    - error
  no-param-reassign:
    - error
    - props: true
  no-proto:
    - error
  no-redeclare:
    - error
    - builtinGlobals: true
  no-restricted-properties:
    - error
  no-return-assign:
    - error
    - except-parens
  no-return-await:
    - warn
  no-script-url:
    - error
  no-self-assign:
    - error
    - props: true
  no-self-compare:
    - error
  no-sequences:
    - error
    - allowInParentheses: true
  no-throw-literal:
    - error
  no-unmodified-loop-condition:
    - error
  no-unused-expressions:
    - error
    - allowShortCircuit: false
      allowTernary: false
      allowTaggedTemplates: false
      enforceForJSX: true
  no-unused-labels:
    - error
  no-useless-call:
    - error
  no-useless-catch:
    - error
  no-useless-concat:
    - error
  no-useless-escape:
    - error
  no-useless-return:
    - error
  no-void:
    - error
    - allowAsStatement: false
  no-warning-comments:
    - warn
  no-with:
    - error
  prefer-named-capture-group:
    - warn
  prefer-promise-reject-errors:
    - error
    - allowEmptyReject: false
  prefer-regex-literals:
    - error
    - disallowRedundantWrapping: true
  radix:
    - error
    - as-needed
  require-await:
    - error
  require-unicode-regexp:
    - error
  vars-on-top:
    - off
  wrap-iife:
    - error
    - inside
    - functionPrototypeMethods: true
  yoda:
    - error
    - never

  # Strict Mode
  strict:
    - error

  # Variables
  init-declarations:
    - off
  no-delete-var:
    - error
  no-label-var:
    - error
  no-restricted-globals:
    - error
  no-shadow:
    - error
    - builtinGlobals: true
      hoist: functions
  no-shadow-restricted-names:
    - error
  no-undef:
    - error
    - typeof: true
  no-undef-init:
    - error
  no-undefined:
    - error
  no-unused-vars:
    - warn
    - vars: all
      args: all
      ignoreRestSiblings: true
      caughtErrors: all
  no-use-before-define:
    - error
    - functions: true
      classes: true
      variables: true

  # Stylistic Issues
  array-bracket-newline:
    - error
    - always
  array-bracket-spacing:
    - error
    - never
  array-element-newline:
    - error
    - consistent
  block-spacing:
    - error
    - always
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  camelcase:
    - error
    - properties: always
      ignoreDestructuring: false
      ignoreImports: false
      ignoreGlobals: false
  capitalized-comments:
    - warn
    - always
  comma-dangle:
    - error
    - always-multiline
  comma-spacing:
    - error
    - before: false
      after: true
  comma-style:
    - error
    - last
  computed-property-spacing:
    - error
    - never
    - enforceForClassMembers: true
  consistent-this:
    - error
    - that
  eol-last:
    - error
    - always
  func-call-spacing:
    - error
    - never
  func-name-matching:
    - warn
    - always
    - considerPropertyDescriptor: true
      includeCommonJSModuleExports: true
  func-names:
    - error
    - always
  func-style:
    - error
    - declaration
    - allowArrowFunctions: true
  function-call-argument-newline:
    - error
    - consistent
  function-paren-newline:
    - error
    - multiline
  id-denylist:
    - off
  id-length:
    - off
  id-match:
    - off
  implicit-arrow-linebreak:
    - error
    - beside
  indent:
    - error
    - 2
  jsx-quotes:
    - error
    - prefer-double
  key-spacing:
    - error
    - beforeColon: false
      afterColon: true
      mode: minimum
      align: value
  keyword-spacing:
    - error
    - before: true
      after: true
  line-comment-position:
    - off
  linebreak-style:
    - error
    - unix
  lines-around-comment:
    - off
  lines-between-class-members:
    - error
    - always
    - exceptAfterSingleLine: true
  max-depth:
    - warn
    - 4
  max-len:
    - error
    - code: 119
      tabWidth: 2
      ignoreComments: false
      ignoreTrailingComments: false
      ignoreUrls: false
      ignoreStrings: false
      ignoreTemplateLiterals: false
      ignoreRegExpLiterals: false
  max-lines:
    - off
  max-lines-per-function:
    - off
  max-nested-callbacks:
    - warn
    - 4
  max-params:
    - off
  max-statements:
    - off
  max-statements-per-line:
    - warn
    - max: 1
  multiline-comment-style:
    - error
    - starred-block
  multiline-ternary:
    - error
    - always-multiline
  new-cap:
    - error
    - newIsCap: true
      capIsNew: false
      properties: true
  new-parens:
    - error
    - always
  newline-per-chained-call:
    - error
    - ignoreChainWithDepth: 2
  no-array-constructor:
    - error
  no-bitwise:
    - off
  no-continue:
    - off
  no-inline-comments:
    - off
  no-lonely-if:
    - error
  no-mixed-operators:
    - error
    - allowSamePrecedence: true
  no-mixed-spaces-and-tabs:
    - error
  no-multi-assign:
    - error
    - ignoreNonDeclaration: false
  no-multiple-empty-lines:
    - error
    - max: 2
  no-negated-condition:
    - error
  no-nested-ternary:
    - off
  no-new-object:
    - error
  no-plusplus:
    - off
  no-restricted-syntax:
    - off
  no-tabs:
    - off
  no-ternary:
    - off
  no-trailing-spaces:
    - error
    - skipBlankLines: false
      ignoreComments: false
  no-underscore-dangle:
    - off
  no-unneeded-ternary:
    - error
    - defaultAssignment: true
  no-whitespace-before-property:
    - error
  nonblock-statement-body-position:
    - error
    - beside
  object-curly-newline:
    - error
    - multiline: true
      consistent: true
  object-curly-spacing:
    - error
    - always
  object-property-newline:
    - error
  one-var:
    - off
  one-var-declaration-per-line:
    - error
    - always
  operator-assignment:
    - error
    - always
  operator-linebreak:
    - error
    - after
  padded-blocks:
    - error
    - never
    - allowSingleLineBlocks: true
  padding-line-between-statements:
    - off
  prefer-exponentiation-operator:
    - error
  prefer-object-spread:
    - error
  quote-props:
    - error
    - consistent-as-needed
    - keywords: true
      unnecessary: true
      numbers: true
  quotes:
    - error
    - double
    - avoidEscape: true
      allowTemplateLiterals: true
  semi:
    - error
    - always
    - omitLastInOneLineBlock: false
  semi-spacing:
    - error
    - before: false
      after: true
  semi-style:
    - error
    - last
  sort-keys:
    - off
  sort-vars:
    - off
  space-before-blocks:
    - error
    - always
  space-before-function-paren:
    - error
    - always
  space-in-parens:
    - error
    - never
  space-infix-ops:
    - error
  space-unary-ops:
    - error
    - words: true
      nonwords: false
  spaced-comment:
    - error
    - always
  switch-colon-spacing:
    - error
    - after: true
      before: false
  template-tag-spacing:
    - error
    - never
  unicode-bom:
    - error
    - never
  wrap-regex:
    - error

  # ECMAScript 6
  arrow-body-style:
    - error
    - as-needed
  arrow-parens:
    - error
    - always
  arrow-spacing:
    - error
    - before: true
      after: true
  constructor-super:
    - error
  generator-star-spacing:
    - error
    - before: true
      after: true
  no-class-assign:
    - error
  no-confusing-arrow:
    - error
    - allowParens: true
  no-const-assign:
    - error
  no-dupe-class-members:
    - error
  no-duplicate-imports:
    - error
    - includeExports: false
  no-new-symbol:
    - error
  no-restricted-exports:
    - off
  no-restricted-imports:
    - off
  no-this-before-super:
    - error
  no-useless-computed-key:
    - error
    - enforceForClassMembers: true
  no-useless-constructor:
    - error
  no-useless-rename:
    - error
    - ignoreImport: false
      ignoreExport: false
      ignoreDestructuring: false
  no-var:
    - error
  object-shorthand:
    - error
    - always
  prefer-arrow-callback:
    - error
    - allowNamedFunctions: false
      allowUnboundThis: false
  prefer-const:
    - error
    - destructuring: any
      ignoreReadBeforeAssign: true
  prefer-destructuring:
    - error
    - array: true
      object: true
    - enforceForRenamedProperties: true
  prefer-numeric-literals:
    - error
  prefer-rest-params:
    - error
  prefer-spread:
    - error
  prefer-template:
    - error
  require-yield:
    - error
  rest-spread-spacing:
    - error
    - never
  sort-imports:
    - error
    - ignoreCase: false
      ignoreDeclarationSort: true
      ignoreMemberSort: false
      memberSyntaxSortOrder: ["none", "all", "multiple", "single"]
      allowSeparatedGroups: true
  symbol-description:
    - error
  template-curly-spacing:
    - error
    - never
  yield-star-spacing:
    - error
    - both
