# Rules: https://mysticatea.github.io/eslint-plugin-eslint-comments/rules/
# Version: 3.2.0
# Last updated: 2021-09-05

rules:
  # Best Practices
  eslint-comments/disable-enable-pair:
    - error
    - allowWholeFile: true
  eslint-comments/no-aggregating-enable:
    - error
  eslint-comments/no-duplicate-disable:
    - error
  eslint-comments/no-unlimited-disable:
    - error
  eslint-comments/no-unused-disable:
    - error
  eslint-comments/no-unused-enable:
    - error

  # Stylistic Issues
  eslint-comments/no-restricted-disable:
    - off
  eslint-comments/no-use:
    - off
  eslint-comments/require-description:
    - error
