# Rules: https://github.com/jest-community/eslint-plugin-jest#rules
# Version: 24.4.0
# Last updated: 2021-09-06

rules:
  jest/consistent-test-it:
    - error
    - fn: test
      withinDescribe: test
  jest/expect-expect:
    - error
    - assertFunctionNames:
        - expect
        - ^expect.*$
  jest/lowercase-name:
    - error
  jest/max-nested-describe:
    - error
    - max: 3
  jest/no-alias-methods:
    - error
  jest/no-commented-out-tests:
    - warn
  jest/no-conditional-except:
    - error
  jest/no-deprecated-functions:
    - error
  jest/no-disabled-tests:
    - warn
  jest/no-done-callback:
    - error
  jest/no-duplicate-hooks:
    - error
  jest/no-export:
    - error
  jest/no-focused-tests:
    - error
  jest/no-hooks:
    - error
  jest/no-identical-title:
    - error
  jest/no-if:
    - error
  jest/no-interpolation-in-snapshots:
    - error
  jest/no-jasmine-globals: 
    - error
  jest/no-jest-import:
    - error
  jest/no-large-snapshots:
    - warn
  jest/no-mocks-import:
    - error
  jest/no-restricted-matchers:
    - off
  jest/no-standalone-expect:
    - error
  jest/no-test-prefixes:
    - error
  jest/no-test-return-statement:
    - error
  jest/prefer-called-with:
    - error
  jest/prefer-expect-assertions:
    - off
  jest/prefer-hooks-on-top:
    - error
  jest/prefer-spy-on:
    - error
  jest/prefer-strict-equal:
    - error
  jest/prefer-to-be-null:
    - error
  jest/prefer-to-be-undefined:
    - error
  jest/prefer-to-contain:
    - error
  jest/prefer-to-have-length:
    - error
  jest/prefer-todo:
    - error
  jest/require-to-throw-message:
    - error
  jest/require-top-level-describe:
    - error
  jest/valid-describe:
    - error
  jest/valid-expect:
    - error
  jest/valid-expect-in-promise:
    - error
  jest/valid-title:
    - error

# TypeScript Rules
overrides:
  - files:
    - tests/**
    rules:
      "@typescript-eslint/unbound-method":
        - off
      jest/unbound-method:
        - error
