# Rules: https://nextjs.org/docs/basic-features/eslint#eslint-plugin
# Version: 12.1.6
# Last updated: 2022-05-07

rules:
  "@next/next/google-font-display":
    - error
  "@next/next/google-font-preconnect":
    - error
  "@next/next/link-passhref":
    - error
  "@next/next/no-css-tags":
    - error
  "@next/next/no-document-import-in-page":
    - error
  "@next/next/no-head-import-in-document":
    - error
  "@next/next/no-html-link-for-pages":
    - error
  "@next/next/no-head-element":
    - error
  "@next/next/no-img-element":
    - error
  "@next/next/no-page-custom-font":
    - error
  "@next/next/no-sync-scripts":
    - error
  "@next/next/no-title-in-document-head":
    - error
  "@next/next/no-unwanted-polyfillio":
    - error
  "@next/next/inline-script-id":
    - error
  "@next/next/no-typos":
    - error
  "@next/next/next-script-for-ga":
    - error
