# Rules: https://github.com/mysticatea/eslint-plugin-node#-rules
# Version: 11.1.0
# Last updated: 2021-09-06

rules:
  # Possible Errors
  node/handle-callback-err:
    - error
  node/no-callback-literal:
    - error
  node/no-exports-assign:
    - error
  node/no-extraneous-import:
    - error
  node/no-extraneous-require:
    - error
  node/no-missing-import:
    - error
  node/no-missing-require:
    - error
  node/no-new-require:
    - error
  node/no-path-concat:
    - error
  node/no-process-exit:
    - error
  node/no-unpublished-bin:
    - error
  node/no-unpublished-import:
    - error
  node/no-unpublished-require:
    - error
  node/no-unsupported-features/es-builtins:
    - error
  node/no-unsupported-features/es-syntax:
    - error
  node/no-unsupported-features/node-builtins:
    - error
  node/process-exit-as-throw:
    - error
  node/shebang:
    - error

  # Best Practices
  node/no-deprecated-api:
    - error

  # Stylistic Issues
  node/callback-return:
    - error
  node/exports-style:
    - error
  node/file-extension-in-import:
    - error
    - never
  node/global-require:
    - error
  node/no-mixed-requires:
    - error
  node/no-process-env:
    - error
  node/no-restricted-import:
    - off
  node/no-restricted-require:
    - off
  node/no-sync:
    - off
  node/prefer-global/buffer:
    - error
    - always
  node/prefer-global/console:
    - error
    - always
  node/prefer-global/process:
    - error
    - always
  node/prefer-global/text-decoder:
    - error
    - always
  node/prefer-global/text-encoder:
    - error
    - always
  node/prefer-global/url-search-params:
    - error
    - always
  node/prefer-global/url:
    - error
    - always
  node/prefer-promises/dns:
    - error
  node/prefer-promises/fs:
    - error
