# Rules: https://github.com/yannickcr/eslint-plugin-react#list-of-supported-rules
# Version: 7.29.4
# Last updated: 2022-05-07

rules:
  react/boolean-prop-naming:
    - error
    - validateNested: true
  react/button-has-type:
    - error
    - button: true
      submit: false
      reset: false
  react/default-props-match-prop-types:
    - error
    - allowRequiredDefaults: false
  react/destructuring-assignment:
    - error
    - always
  react/display-name:
    - warn
    - ignoreTranspilerName: false
  react/forbid-component-props:
    - error
  react/forbid-dom-props:
    - off
  react/forbid-elements:
    - off
  react/forbid-foreign-prop-types:
    - error
  react/forbid-prop-types:
    - error
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
  react/hook-use-state:
    - error
  react/iframe-missing-sandbox:
    - error
  react/no-access-state-in-setstate:
    - error
  react/no-adjacent-inline-elements:
    - error
  react/no-array-index-key:
    - error
  react/no-arrow-function-lifecycle:
    - error
  react/no-children-prop:
    - error
  react/no-danger:
    - error
  react/no-danger-with-children:
    - error
  react/no-deprecated:
    - error
  react/no-did-mount-set-state:
    - error
    - disallow-in-func
  react/no-did-update-set-state:
    - error
    - disallow-in-func
  react/no-direct-mutation-state:
    - error
  react/no-find-dom-node:
    - error
  react/no-invalid-html-attribute:
    - error
  react/no-is-mounted:
    - error
  react/no-multi-comp:
    - off
  react/no-namespace:
    - error
  react/no-redundant-should-component-update:
    - error
  react/no-render-return-value:
    - error
  react/no-set-state:
    - off
  react/no-string-refs:
    - error
  react/no-this-in-sfc:
    - error
  react/no-typos:
    - error
  react/no-unescaped-entities:
    - error
  react/no-unknown-property:
    - error
  react/no-unsafe:
    - error
    - checkAliases: true
  react/no-unstable-nested-components:
    - error
    - allowAsProps: false
  react/no-unused-class-component-methods:
    - error
  react/no-unused-prop-types:
    - error
  react/no-unused-state:
    - error
  react/no-will-update-set-state:
    - error
    - disallow-in-func
  react/prefer-es6-class:
    - error
    - always
  react/prefer-exact-props:
    - error
  react/prefer-read-only-props:
    - error
  react/prefer-stateless-function:
    - error
    - ignorePureComponents: false
  react/prop-types:
    - error
  react/react-in-jsx-scope:
    - off
  react/require-default-props:
    - off
  react/require-optimization:
    - off
  react/require-render-return:
    - error
  react/self-closing-comp:
    - error
    - component: true
      html: true
  react/sort-comp:
    - error
  react/sort-prop-types:
    - off
  react/state-in-constructor:
    - error
    - always
  react/static-property-placement:
    - error
    - "static public field"
  react/style-prop-object:
    - error
  react/void-dom-elements-no-children:
    - error

  # JSX-specific Rules
  react/jsx-boolean-value:
    - error
    - never
  react/jsx-child-element-spacing:
    - error
  react/jsx-closing-bracket-location:
    - error
    - tag-aligned
  react/jsx-closing-tag-location:
    - error
  react/jsx-curly-brace-presence:
    - error
    - props: never
      children: never
  react/jsx-curly-newline:
    - off
  react/jsx-curly-spacing:
    - error
    - when: never
  react/jsx-equals-spacing:
    - error
    - never
  react/jsx-filename-extension:
    - error
    - allow: as-needed
      extensions: [".tsx"]
  react/jsx-first-prop-new-line:
    - error
    - multiline
  react/jsx-fragments:
    - error
    - syntax
  react/jsx-handler-names:
    - error
    - eventHandlerPrefix: "handle"
      eventHandlerPropPrefix: "on"
      checkLocalVariables: true
      checkInlineFunction: true
  react/jsx-indent:
    - error
    - 2
    - checkAttributes: true
      indentLogicalExpressions: true
  react/jsx-indent-props:
    - error
    - 2
  react/jsx-key:
    - warn
    - checkFragmentShorthand: true
      checkKeyMustBeforeSpread: true
  react/jsx-max-depth:
    - off
  react/jsx-max-props-per-line:
    - off
  react/jsx-newline:
    - off
  react/jsx-no-bind:
    - error
    - ignoreDOMComponents: false
      ignoreRefs: false
      allowArrowFunctions: false
      allowFunctions: false
      allowBind: false
  react/jsx-no-comment-textnodes:
    - warn
  react/jsx-no-constructed-context-values:
    - warn
  react/jsx-no-duplicate-props:
    - error
    - ignoreCase: true
  react/jsx-no-literals:
    - off
  react/jsx-no-script-url:
    - error
  react/jsx-no-target-blank:
    - error
  react/jsx-no-undef:
    - error
    - allowGlobals: true
  react/jsx-no-useless-fragment:
    - error
    - allowExpressions: true
  react/jsx-one-expression-per-line:
    - error
  react/jsx-pascal-case:
    - error
    - allowAllCaps: false
      allowLeadingUnderscore: false
      allowNamespace: false
  react/jsx-props-no-multi-spaces:
    - error
  react/jsx-props-no-spreading:
    - error
    - html: enforce
      custom: enforce
      explicitSpread: enforce
  react/jsx-sort-default-props:
    - off
  react/jsx-sort-props:
    - off
  react/jsx-tag-spacing:
    - error
    - closingSlash: never
      beforeSelfClosing: always
      afterOpening: never
      beforeClosing: never
  react/jsx-uses-react:
    - off
  react/jsx-uses-vars:
    - off
  react/jsx-wrap-multilines:
    - error
    - declaration: parens-new-line
      assignment: parens-new-line
      return: parens-new-line
      arrow: parens-new-line
      condition: parens-new-line
      logical: parens-new-line
      prop: parens-new-line
