# Rules: https://www.npmjs.com/package/eslint-plugin-react-hooks
# Version: 4.3.0
# Last updated: 2022-01-05

rules:
  react-hooks/rules-of-hooks:
    - error
  react-hooks/exhaustive-deps:
    - warn
