# Rules: https://github.com/francoismassart/eslint-plugin-tailwindcss#supported-rules
# Version: 3.0.3
# Last updated: 2022-01-05

rules:
  tailwindcss/classnames-order:
    - error
  tailwindcss/migration-from-tailwind-2:
    - error
  tailwindcss/no-custom-classname:
    - error
  tailwindcss/no-contradicting-classname:
    - error
